jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "Building..."
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
